from niko.roboter import *
roboter=Roboter('test.welt', 0.1)
roboter.vor()
roboter.vor()
roboter.vor()
roboter.vor()
roboter.links()
roboter.vor()
roboter.vor()
roboter.vor()
roboter.vor()
roboter.vor()
roboter.links()
roboter.vor()
roboter.vor()
roboter.vor()
roboter.vor()
roboter.links()
roboter.vor()
roboter.links()
roboter.links()
roboter.vor()
roboter.vor()
roboter.links()
roboter.links()
roboter.vor()
roboter.vor()
roboter.vor()
